// colors
export const colorMainBackground = 'rgb(218, 224, 230)'
export const colorComponentsBackground = 'white'
export const colorLightGrayBackground = 'rgb(246, 247, 248)'
export const colorBorderLightGrey = 'rgb(204, 204, 204)'
export const colorBorderDarkGrey = 'rgb(137, 137, 137)'
export const colorPrimary = '#007bff'
export const colorLightPrimary = 'rgba(0, 121, 211, 0.2)'
export const colorSecondary = '#6c757d'
export const colorGold = '#ffc107'
export const colorRed = '#ff4500'
export const colorLightRed = '#ff6a32'
export const colorDarkRed = '#af2f00'
export const colorBlack = 'black'

// font
export const fontsizeLarge = '18px'
export const fontsizeMedium = '14px'
export const fontsizeSMedium = '12px'
export const fontsizeSmall = '10px'